#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

install_version="1.6.1.0"
download_link_1_6_1_1="https://www.prestashop.com/download/old/prestashop_1.6.1.1.zip"
download_link_1_6_1_0="https://www.prestashop.com/download/old/prestashop_1.6.1.0.zip"
download_link_1_6_0_14="https://www.prestashop.com/download/old/prestashop_1.6.0.14.zip"
download_link=${download_link_1_6_1_0}
download_file=prestashop_${install_version}.zip

current_version_dir=${OPENSHIFT_DATA_DIR}current

#
# If PrestaShop is already installed in the current gear, there
# is nothing to build :-)
#
[ -d "${current_version_dir}" ] && exit 0

# Download the latest stable version from mirror
install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}
mkdir -p $install_dir
pushd ${install_dir} >/dev/null
curl -Ls ${download_link} > ${download_file}

# Install PrestaShop
unzip ${download_file}
rm -rf ${download_file}
rm Install_PrestaShop.html
mv prestashop php

echo ${install_version} > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version

popd > /dev/null

