#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

dest_dir=${OPENSHIFT_DATA_DIR}current

current_version=$(cat ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version)
install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${current_version}

if [ ! -d "${dest_dir}" ]; then
  mkdir -p $dest_dir
  cp -rf ${install_dir}/prestashop/* ${dest_dir}/
fi

# Replace the php/ directory with provided clean PrestaShop installation
if [ -d ${OPENSHIFT_REPO_DIR}php ]; then
  rm -rf ${OPENSHIFT_REPO_DIR}php
fi
ln -sf ${dest_dir} ${OPENSHIFT_REPO_DIR}php

#if [ ! -f ${OPENSHIFT_DATA_DIR}config/settings.inc.php ]; then
#    mkdir -p ${OPENSHIFT_DATA_DIR}config
#    touch ${OPENSHIFT_DATA_DIR}config/settings.inc.php
#fi
#ln -sf ${OPENSHIFT_DATA_DIR}config/settings.inc.php ${OPENSHIFT_REPO_DIR}php/config/settings.inc.php

# Check and wait for MySQL
if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi
